language: android

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.10

jdk:
  - oraclejdk8

android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+

env:
  matrix:
    - COMPILE_METHOD=check
    - COMPILE_METHOD=assembleDebug


script: ./gradlew $COMPILE_METHOD -PdisablePreDex

notifications:
  slack:
    secure: EzftlFYHtgFuBpRsSleKtsA1PngiK/tKHw8WrFfFU69ehXvvdA1Bi5t+TBn9eFo4E5cRolrPuyMGn8HyMLYn1RFAvr3YcSPIll++92OeyV0C9Opx68aK3iCoIXuasZ0Id3By1mnjefRuQvMQShfHBe/7lbtPvip254H9QX57fl4=